<a href="https://colab.research.google.com/github/henrykibithia8-dev/DS-projests/blob/main/Multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
#load data
data = pd.read_csv("https://github.com/henrykibithia8-dev/DS-projests/raw/main/Multiple%20linear%20regression.csv")

data

,SAT,"Rand 1,2,3",GPA
0,1714,1,2.40
1,1664,3,2.52
2,1760,3,2.54
3,1685,3,2.74
4,1693,2,2.83
...,...,...,...
79,1936,3,3.71
80,1810,1,3.71
81,1987,3,3.73
82,1962,1,3.76


In [3]:
data.describe()

,SAT,"Rand 1,2,3",GPA
count,84.000000,84.000000,84.000000
mean,1845.273810,2.059524,3.330238
std,104.530661,0.855192,0.271617
min,1634.000000,1.000000,2.400000
25%,1772.000000,1.000000,3.190000
50%,1846.000000,2.000000,3.380000
75%,1934.000000,3.000000,3.502500
max,2050.000000,3.000000,3.810000


Create Multiple LinearRegression

In [4]:
#declaring the dependent and independent variable
x = data.drop(["GPA"], axis = 1)
y = data["GPA"]

Declare the LinearRegression

In [5]:
#model
reg = LinearRegression()

In [6]:
#fit the regression into data
reg.fit(x,y)

LinearRegression()

In [7]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [8]:
reg.intercept_

np.float64(0.29603261264909486)

In [9]:
reg.score(x,y)

0.4066811952814283

In [10]:
reg.predict(pd.DataFrame(data=[[5000, 2]], columns=["SAT", "Rand 1,2,3"]))

array([8.54720197])

In [11]:
reg.score(x,y)

0.4066811952814283

In [12]:
x.shape

(84, 2)

In [13]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adr2 = 1-(1-r2)*(n-1)/(n-p-1)
adr2

0.3920313482513401

Feature selection

In [14]:
from sklearn.feature_selection import f_regression

print(f"f_statistics: {f_regression(x,y)}")

f_statistics: (array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))


In [15]:
p_values = f_regression(x,y)[1]
p_values.round(3)

array([0.   , 0.676])

Creating a summary table

In [16]:
#dataframe
df = pd.DataFrame(data=["SAT", "Rand 1 2 3"], columns=["features"])
df

,features
0,SAT
1,Rand 1 2 3


In [17]:
reg_summary= pd.DataFrame(data = x.columns.values, columns= ["Features"])
df

,features
0,SAT
1,Rand 1 2 3


In [18]:
#now  summary for coef and p_values
reg_summary["coeficient"] = reg.coef_
reg_summary["p_values"] = p_values.round(3)
reg_summary

,Features,coeficient,p_values
0,SAT,0.001654,0.000
1,"Rand 1,2,3",-0.008270,0.676


In [20]:
x = data.drop(["Rand 1,2,3", "GPA"], axis = 1)
x

,SAT
0,1714
1,1664
2,1760
3,1685
4,1693
...,...
79,1936
80,1810
81,1987
82,1962
