In [116]:
import numpy as np

In [117]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [118]:
print(type(arr))

<class 'numpy.ndarray'>


In [119]:
arr.ndim

1

In [120]:
#printing my first array
print(arr[0])

1


In [121]:
#What is a correct syntax to print the number 8 from the array below:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1,2])

8


In [122]:
arr.shape

(2, 5)

In [123]:
#What is a correct syntax to print the numbers [3, 4, 5] from the array below:

arr = np.array([1,2,3,4,5,6,7])

print(arr[2:5])

[3 4 5]


In [124]:
#Which syntax would print the last 4 numbers from the array below:

arr = np.array([1,2,3,4,5,6,7])
print(arr[-4:])

[4 5 6 7]


In [125]:
#Which syntax would print every other item from the array below:

arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [126]:
print(arr.dtype)

int32


In [127]:
#What is a correct syntax to create an array of type float?
arr = np.array([1, 2, 3], dtype = float)
print(arr)

[1. 2. 3.]


In [128]:
np.shape

<function shape at 0x000001F9142443B0>

In [129]:
#joining two 1d or more arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

joined = np.concatenate((arr1, arr2))
joined

array([1, 2, 3, 4, 5, 6])

In [130]:
#joining 2d arrays 
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
joined2 = np.concatenate((arr3, arr4))
joined2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [131]:
joined2.shape

(4, 2)

In [136]:
import pandas as pd
print(pd.options.display.max_rows) 


60
