<a href="https://colab.research.google.com/github/henrykibithia8-dev/DS-projests/blob/main/Simple_linear_regression_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simple linear regression

## Import the relevant libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load the data

In [60]:
from google.colab import drive
drive.mount('/content/drive')
#load data
from google.colab import files
uploaded = files.upload() # This opens a file picker

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Saving Simple linear regression.csv to Simple linear regression (3).csv


In [4]:
data = pd.read_csv("Simple linear regression.csv")
data

ParserError: Error tokenizing data. C error: Expected 1 fields in line 38, saw 2


## Create the regression

### Declare the dependent and independent variables

In [120]:
x = data.drop(['GPA'], axis= 1)
y = data['GPA']

In [121]:
x.shape

(84, 1)

In [122]:
y.shape

(84,)

### Regression itself

In [123]:
reg = LinearRegression()

In [124]:
reg.fit(x,y)

LinearRegression()

In [125]:
#lets get R_squared
reg.score(x, y)

0.40600391479679754

In [126]:
reg.coef_

array([0.00165569])

In [127]:
reg.intercept_

np.float64(0.2750402996602799)

In [128]:
import numpy as np
#predict new data
reg.predict(np.array(1740).reshape(-1, 1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3.15593751])

In [129]:
import numpy as np
new_data = pd.DataFrame(data=[[1740, np.nan], [1760, np.nan]], columns=["SAT", "GPA"])
new_data

,SAT,GPA
0,1740,NaN
1,1760,NaN


In [131]:
reg.predict(new_data[['SAT']])

array([3.15593751, 3.18905127])

In [1]:
plt.scatter(x,y)
yhat = reg.coef_*x + reg.intercept_
fig = plt.plot(x, yhat, c = "w")
plt.show()

NameError: name 'plt' is not defined